### ISSUE TITLE
mess menu needs to be updated.

### ISSUE THREAD

**Issue by sidarchv** [vaibhavraj-exe/Whats-in-mess#2]
Just paste the given text in the menu part of **script.js** to update the menu.
[updated_menu.txt](https://github.com/vaibhavraj-exe/Whats-in-mess/files/10715971/updated_menu.txt)

![IMG-20230207-WA0022.jpg](https://user-images.githubusercontent.com/100599424/218409123-352a6202-0355-4c23-8bcf-4b213037ffed.jpg)

**Comment by vaibhavraj-exe** [comment]
Since I see you have closed the issue, I think you have realized that the menu is actually updated, but the mistake I did was that I didn't update the date 😅, which I will be doing today, any how I am glad that you contacted, and do let me know if you face any issue in the future.

**Comment by vaibhavraj-exe** [comment]
Hah.. so they updated the menu for real. Yesterday though 😅, will update today, thanks for informing!

**Comment by mohitbaggu** [comment]
[updated_menu.txt](https://github.com/vaibhavraj-exe/Whats-in-mess/files/10715971/updated_menu.txt)

**Comment by vaibhavraj-exe** [comment]
Yah.. finally done .. sorry for delay.
